AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
    ExpressApi:
      Type: AWS::Serverless::HttpApi

    BookTestFunction:
      Type: 'AWS::Serverless::Function'
      Properties:
        CodeUri: src/handler/
        Handler: booking.handler
        Runtime: nodejs14.x
        Events:
          ProxyApiRoot:
            Type: HttpApi
            Properties:
              ApiId: !Ref ExpressApi

Outputs:
  BookTestFunction:
    Description: "API Gateway endpoint URL for GetLambdaFunction on dev stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Dev/"
  BookTestApp:
    Description: "Get Lambda Function ARN"
    Value: !GetAtt GetLambdaFunction.Arn
